### PR TITLE
Use Google Fonts CDN for fonts instead of including the font in the repo

### PR DESCRIPTION
**Pull request by simonrodrig**
Since the fonts that you are using are Google Fonts, you can import the fonts using Google Fonts's CDN instead of including them in the repo. This should reduce file size and load times.

### CODE REVIEW

**Comment by itspaulyg** [comment]
Thanks for the PR but two things I'm thinking: 

1. Does this still work when testing locally? I assume it just requires a connection. 
2. Even though load times for files might decrease (less files), wouldn't this cause the user to make a request each time they load they page, even switch pages? The files may cause a higher load initially but then should be cached from there on out I would believe.

**Comment by simonrodrig** [comment]
Good questions!

1. I am not 100% sure what you mean by "locally" in this case. If you asking if loading fonts using a CDN will work if opening the HTML file in a browser, then yes, that use case will still work. Or, do you mean if the website will work without an internet connection? The answer is likely no, unless the font is installed globally on your computer. It's typically common practice to include fallback fonts in your CSS in the event of some network error, which I can add to this PR as well. Let me know if I got your question right.
2. Most browsers cache assets on a website, including fonts, so the only time the browser would actually make a network request is on very first page load, and thus if you click around the website, you will be using a cached version of the font, even on different pages. I think it might also intuitively seem that storing the fonts in the repo would be faster, but because browsers don't give you access to the filesystem, opening a font locally on the repo is still technically making a network request, and thus you would be limited to however fast GitHub Pages's hardware can deliver the font.

**Comment by itspaulyg** [comment]
Awesome! For 1, that is what I was referring too. I figured what you said but just wanted to make sure. It seems smart to include them just in case as well but then I do assume the import would take precedence over the font-face, so then it can work and be as fast as possible (hopefully). For 2 it makes sense that the browser would still cache the font after the first load, I guess I was thinking the file system was loaded and thus making storing the fonts faster. 

Overall, I would say include both for a fail safe but also thanks for the idea and PR of Google Font's CDN.

**Comment by simonrodrig** [comment]
Good to hear! 

Just to clarify my point about fallback fonts, what I meant was that in CSS, you can specfiy multiple fonts to act as a fallback if the initial font doesn't load for some reason. For example:

```css
p {
    font-family: 'Roboto', sans-serif
}
```

First, CSS will attempt to use Roboto, but if the font cannot load for any reason, it will default to the default sans-serif font on your device.

**Pull request merged**
